config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit] do
    resources :listings do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
end

resources :listings, controller: "listings" do
  resources :reservations, controller: "reservations"
end


  get "/welcome" => "welcome#index", as: "welcome"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  get "users/:user_id/listings/:id/verify" => "listings#verify", as: "verify"
  get "/reservations/:id/checkout" => "braintree#new", as: "reservation_payment"

  post 'braintree/checkout'

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
  class Authentication < ApplicationRecord
     belongs_to :user

     def self.create_with_omniauth(auth_hash)
       self.new(
         provider: auth_hash["provider"],
         uid: auth_hash["uid"],
         token: auth_hash["credentials"]["token"]
       )
     end

     def update_token(auth_hash)
       self.token = auth_hash["credentials"]["token"]
       self.save
     end
  end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
	enum verification: [:not_verified, :verified]
	mount_uploaders :avatars, AvatarUploader
	has_many :reservations

	def self.search(search)
  where("property_type LIKE ? OR description LIKE ?", "%#{search}%", "%#{search}%") 
end

end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :user
	belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
    has_many :authentications, dependent: :destroy
    has_many :listings
    has_many :reservations
    
    enum role: [:customer, :moderator, :admin]
    mount_uploaders :avatars, AvatarUploader
    serialize :avatars, JSON # If you use SQLite, add this line.
    def self.create_with_auth_and_hash(authentication, auth_hash)
      
      user = self.create!(
        # name: auth_hash["name"],
        email: auth_hash["extra"]["raw_info"]["email"],
        password: SecureRandom.hex(5)
      )
      user.authentications << authentication
      return user
    end

    # grab fb_token to access Facebook for user data
    def fb_token
      x = self.authentications.find_by(provider: 'facebook')
      return x.token unless x.nil?
    end

 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception

def allowed?(action:, user:)
    # implement some code
  end


end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
	def new
  @client_token = Braintree::ClientToken.generate
end

def checkout
  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

  result = Braintree::Transaction.sale(
   :amount => "10.00", #this is currently hardcoded
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

  if result.success?
    UserMailer.notify(current_user).deliver_now
    redirect_to :root, :flash => { :success => "Transaction successful!" }
  else
    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
  end 
end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  
  def index

    if params[:search]
      @listing_search = Listing.search(params[:search]).order("created_at DESC")
    end

  	@listing = Listing.all.where(user_id: params[:user_id])
    @listing = Listing.paginate(:page => params[:page], :per_page => 5)
    unless @listing.empty?
    else
  		@listing = "You have no new listings!"
  	end 

    @full_list = Listing.all
    @full_list=Listing.paginate(:page => params[:page], :per_page => 5)

    @reservation = Reservation.all.where(user_id: current_user.id)
    if @reservation.empty?
      @reservation = "You have no reservations."
    else
      @reservation
    end

end

  def create
  	@listing = current_user.listings.new(listing_params)
	@listing.save
	redirect_to user_listings_path
	end


   def new
    @listing = Listing.new
  end

  def destroy
    @delete_listing=Listing.find(params[:id])
    @delete_listing.destroy
    redirect_to user_listings_path
  end

  def show
  end

  def edit
    @editlist = Listing.find(params[:id])
  end

  def update
    @edit_list = Listing.find(params[:id])
    @edit_list.update(property_type: params[:listing][:property_type], description: params[:listing][:description], price: params[:listing][:price])
    redirect_to user_listings_path
  end

  def verify
    Listing.find(params[:id]).update(verification: "verified")
    redirect_to user_listings_path(params[:user_id])
  end

  def show 
    @show = Listing.find(params[:id])
  end

  private

  def listing_params
    params.require(:listing).permit(:property_type, :description, :price, {avatars: []})
  end
#   def index
#   @listings = Listing.all.where(user_id: params[:user_id])
#   if params[:search]
#     @listings = Listing.search(params[:search]).order("created_at DESC")
#   else
#     @listings = Listing.all.order("created_at DESC")
#   end
# end

  end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

 def new
    @listing = Listing.find(params[:listing_id])
    @reservation = Reservation.new
  end

 def create
    @reservation = current_user.reservations.new(reservation_params)
    @reservation.listing_id = params[:listing_id]
    if @reservation.save
      redirect_to user_listings_path(current_user.id)
    else
      render :new
    end
  end
  

private
  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  def create
    @user = authenticate(params)

    sign_in(@user) do |status|
      if status.success?
        redirect_to welcome_path
      else
        flash.now.notice = status.failure_message
        render template: "sessions/new", status: :unauthorized
      	end
  	end
	end

  def create_from_omniauth
      auth_hash = request.env["omniauth.auth"]
      authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

      # if: previously already logged in with OAuth
      if authentication.user
        user = authentication.user
        authentication.update_token(auth_hash)
        @next = welcome_path
        @notice = "Signed in!"
      # else: user logs in with OAuth for the first time
      else
        user = User.create_with_auth_and_hash(authentication, auth_hash)
        # you are expected to have a path that leads to a page for editing user details
        @next = edit_user_path(user)
        @notice = "User created. Please confirm or edit details"
      end

      sign_in(user)
      redirect_to @next, :notice => @notice
    end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  
  def edit
  end

  def new
  end

  def redirect_signed_in_user
  	if signed_in?
  		redirect_to "/welcome"
  	end 
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		sign_in @user
  		redirect_to welcome_path
  	else
  		render template: "users/new"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

end

#when you create a users controller.
#inherit clearance:UserController 
#and change redirect_to *page you want*

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/braintree/new.html.erb
<h1>Braintree#new</h1>
<p>Find me in app/views/braintree/new.html.erb</p>

<div class="container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
    <div class="demo-frame">  

      <%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>

        <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
        <div id="card-number" class="hosted-field"></div>

        <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>      
        <div id="expiration-date" class="hosted-field"></div>

        <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
        <div id="cvv" class="hosted-field"></div>

        <%= form.hidden_field "payment_method_nonce" %>

        <div class="button-container">
          <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
        </div>
      <% end %>
    </div>  
  </div>
</div>
</div>
<!-- Load the required client component. -->
<script src="https://js.braintreegateway.com/web/3.19.1/js/client.min.js"></script>

<!-- Load Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.19.1/js/hosted-fields.min.js"></script>
(
<script>
$(document).on("turbolinks:load", function(){
var form = document.querySelector('#cardForm');
var submit = document.querySelector("#submit-payment-btn");

braintree.client.create({
  // Replace this with your own authorization.
  authorization: "<%= @client_token %>"
}, function (clientErr, clientInstance) {
  if (clientErr) {
    // Handle error in client creation
    return;
  }

  braintree.hostedFields.create({
    client: clientInstance,
    styles: {
      'input': {
        'font-size': '14pt'
      },
      'input.invalid': {
        'color': 'red'
      },
      'input.valid': {
        'color': 'green'
      }
    },
    fields: {
      number: {
        selector: '#card-number',
        placeholder: '4111 1111 1111 1111'
      },
      cvv: {
        selector: '#cvv',
        placeholder: '123'
      },
      expirationDate: {
        selector: '#expiration-date',
        placeholder: '10/2019'
      }
    }
  }, function (hostedFieldsErr, hostedFieldsInstance) {
    if (hostedFieldsErr) {
      // Handle error in Hosted Fields creation
      return;
    }

    submit.removeAttribute('disabled');

    form.addEventListener('submit', function (event) {
      event.preventDefault();

      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
        if (tokenizeErr) {
          // Handle error in Hosted Fields tokenization
          return;
        }

        // Put `payload.nonce` into the `payment_method_nonce` input, and then
        // submit the form. Alternatively, you could send the nonce to your server
        // with AJAX.
        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
        form.submit();
      });
    }, false);
  });
});
})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<!DOCTYPE html>
<html>
<head>
<style>
ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: #333;
}

li {
    float: left;
    border-right:1px solid #bbb;
}

li:last-child {
    border-right: none;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: #111;
}

.active {
    background-color: #4CAF50;
}
</style>
</head>
<body>

<ul>
  <li><a class="active" href="#home">Home</a></li>
  <% if current_user != nil%>
  <li><%= link_to "Listings", user_listings_path(user_id: current_user.id) %></li>
  <li style="float:right"><%= link_to "Sign Out", sign_out_path, method: :delete%></li>
  <% end %>
</ul>
<br>
<br>

</body>
</html>


  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div> 

  

  <%= yield %>
<br>

</body>

</html>

app/views/listings/_form.html.erb
<div>
  <%= form.label :property_type %>
  <%= form.text_field :property_type %>

 <%= form.label :description %>
  <%= form.text_field :description %>

 <%= form.label :price %>
  <%= form.text_field :price %>

  <div class="field">
    <%= form.label :avatars %><br>
     <%= form.file_field :avatars, multiple: true %>
  </div>

 
</div>

app/views/listings/edit.html.erb
<p>This is your current listings </p>
<%=@editlist.property_type%>
<%=@editlist.description%>
<%=@editlist.price%>

<p> Edit to:</p>
<%= form_for [current_user, @editlist] do |form| %>
	<%= render partial: '/listings/form', object: form %>
	<%= form.submit %>
	<% end %>

app/views/listings/index.html.erb
<br>
  <center><%= form_tag(@listings, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Listings" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<% if @listing_search.blank? %>
  <h4>There are no listings containing the term <%= params[:search] %>.</h4>
<% else %>
  <tr>
  <% @listing_search.each do |t| %>
    <td><%= t.property_type %></td>
    <td><%= t.description %></td>
    <td><%= t.price %></td>
  </tr><br>
  <% end %>
<% end %>

<%= link_to "Make a new listing", new_user_listing_path(current_user.id) %>


<p><b>Your Listing</b></p>
<% if @listing.is_a? String %>
	<%= @listing %>
	<% else %>
	<table>
  <tr>
  <td>Property Type</td>
  <td>Description</td>
  <td>Price</td>
  <tr><br>
  </table>
  <% @listing.each do |list| %>
  <td><%= list.property_type %> </td>
  <td><%= list.description %></td>
  <td><%= list.price %></td><br>

<% if list.avatars.empty? %>
<% "no picture uploaded" %>
<% else %>
<%list.avatars.each do |photo| %>
<%= image_tag photo.thumb.url %>
<%end%>
<% end %>

  <td><%=link_to "edit" , edit_user_listing_path(current_user.id, list.id)%></td>
  <td><%= link_to "delete" , user_listing_path(current_user.id, list.id), method: :delete, data:{confirm: "are you sure?"} %></td><br>
  </tr> 
  <% end %>
<% end %>

<%= will_paginate @listing %>


<p><b>Full Listing</b></p>
<% if @listing.is_a? String %>
  <%= @listing %>
  <% else %>
  <table>
  <tr>
  <td>Property Type</td>
  <td>Description</td>
  <td>Price</td>
  <tr><br>
  </table>
  <% @listing.each do |list| %>
  <td><%= list.property_type %> </td>
  <td><%= list.description %></td>
  <td><%= list.price %></td><br>
  <td></td>

<td><%= button_to("Check Availability", new_listing_reservation_path(list.id), method: :get) %></td>

      <% if list.verified? %>
  <td><%= "verified property" %></td>
    <% else %>
  <td><%= "non-verified property" %></td>
      <% if current_user.admin? %>
  <td>
      <%= form_for [User.find(list.user_id), list],  method: :patch do |f| %>

        <%= f.label :verification %>
        <%= f.select :verification, options_for_select([["Not Verified", "not_verified"], ["Verified", "verified"]]) %>
        <%= f.submit :submit %>
      <% end %>
  </td><br>
 

      <% end %>
    <% end %>
   <% end %>
  <% end %>

<%= will_paginate @listing %>

app/views/listings/new.html.erb
<div>
<%= form_for [current_user, @listing] do |form| %>
<%= render partial: '/listings/form', object: form %>
<%= form.submit %> 
<% end %>
</div>

app/views/listings/show.html.erb
<% @show.image.each do |photo| %>
    <p><%= image_tag list.avatars[0].url %></p>
    <% end %>
<p><%= @show.property_type %></p>
<p><%= @show.description %></p>
<p><%= @show.price %></p>


<%= link_to "back to user", user_listings_path(current_user.id)%> 

app/views/reservations/new.html.erb
<p> reservation page </p>

<table>
<td><%= @listing.property_type %></td>
<td><%= @listing.description %></td>
<td><%= @listing.price %></td>
<td><%= @listing.verification %></td>
</table>

<div>
<%= form_for [@listing, @reservation] do |form| %>
<%= form.label :start_date %>
<%= form.date_field :start_date %>
<%= form.label :end_date %>
<%= form.date_field :end_date %>
<%= form.submit %>
<% end %>
</div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>
 

 

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<center><h1>Welcome to Airbnb_Faiz</h1></center>

<br>
<center><body>
    <button id = 'chuck'>Just For Fun!</button>
    <div id="gif-container"></div>

<div class="container">
  <h2>Go Places</h2>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

    <div class="item active">
        <img src="http://www.telegraph.co.uk/content/dam/Travel/Destinations/Asia/Malaysia/KL-travel-AP92828955-xlarge.jpg" style="width:100%;">
        <div class="carousel-caption">
          <h3>Kuala Lumpur</h3>
          <p>Kuala Lumpur Love!</p>
        </div>
      </div>

      <div class="item">
        <img src="http://www.telegraph.co.uk/content/dam/video_previews/x/5/x5cgi0ode66q6vuxezqmehmexwer6bt-xlarge.jpg" alt="London" style="width:100%;">
        <div class="carousel-caption">
          <h3>London</h3>
          <p>London is always so much fun!</p>
        </div>
      </div>

      <div class="item">
        <img src="https://worldstrides.com/wp-content/uploads/2015/07/12-Chureito-pagoda-and-Mount-Fuji-Japan.jpg" alt="Japan" style="width:100%;">
        <div class="carousel-caption">
          <h3>Japan</h3>
          <p>Thank you, Japan!</p>
        </div>
      </div>
    
      <div class="item">
        <img src="https://s-media-cache-ak0.pinimg.com/originals/34/ba/90/34ba90fb638a0a4e05cf863ad7341a2b.jpg" style="width:100%;">
        <div class="carousel-caption">
          <h3>New York</h3>
          <p>We love the Big Apple!</p>
        </div>
      </div>
  
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</html>

</body>